services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    depends_on:
      - redis

  client:
    build: ./client
    container_name: client
    ports:
      - "5101:5101"
    depends_on:
      - server
